apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: ivolve
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::800770414458:role/ivolve-eks-cluster-external-secrets-role

---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: ivolve
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets-sync
  namespace: ivolve
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: app-secret 
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: ivolve/app-secrets
        property: DB_PASSWORD
    - secretKey: DB_ROOT_PASSWORD
      remoteRef:
        key: ivolve/app-secrets
        property: DB_ROOT_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: ivolve/app-secrets
        property: JWT_SECRET